# Replace these two values with the exact ones shown in
# SonarQube Cloud > Your Project > Administration > Analysis Method.
sonar.projectKey=MonishKD_ERROR404-SOEN341_Project_W26
sonar.organization=monish-das

sonar.sources=backend/src
sonar.tests=backend/tests
sonar.test.inclusions=backend/tests/**/*.test.js
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info
